blank_issues_enabled: false
contact_links:
  - name: Town of Us: Mira issues
    url: https://github.com/AU-Avengers/TOU-Mira/issues
    about: Bugs in the base Town of Us: Mira mod should be reported there.
