namespace MiraUnleashed.Networking;

public enum MiraUnleashedRpc : uint
{
    TrapperPlaceTrap,
    TrapperTriggerTrap,
    SetLawyerClient,
    SendLawyerChat,
    SendClientChat,
    WitchSpell,
    WitchSpellNotification,
    LawyerObject,
    ForestallerReveal,
    WraithPlaceLantern,
    WraithReturnLantern,
    WraithBreakLantern,
    MiragePlaceDecoy,
    MirageDestroyDecoy,
    MirageTriggerDecoy,
    MiragePrimeDecoy,
    WitchClearAllSpellbound,
    WitchClearSpellboundPlayer,
    WitchClearSpellboundByWitch,
    HackerActivateJam,
    HackerStartJam,
    HackerSetJamCharges,
    HackerResetRound,
    InjectorInject,
    CharlatanConcealStart,
    CharlatanConcealComplete,
    CharlatanConcealCancel,
    CharlatanDeceiveActivate,
    ScavengerEat,
    ScavengerScavenge,
}
